### ISSUE TITLE
Probably wrong indexing

### ISSUE THREAD

**Issue by Luonic** [batzner/indrnn#7]
in ind_rnn_cell.py:
```
def build(self, inputs_shape):
    if inputs_shape[1].value is None:
      raise ValueError("Expected inputs.shape[-1] to be known, saw shape: %s"
                       % inputs_shape)
```
if `inputs_shape[1].value is None:` should be if `inputs_shape[-1].value is None:` because we need to check if depth is defined

**Comment by batzner** [comment]
The `IndRNNCell` code is an adaptation from TensorFlow's `BasicRNNCell`, which [also uses `inputs_shape[1]`](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/python/ops/rnn_cell_impl.py#L331). I think it doesn't make a difference whether you use 1 or -1, because the inputs must be 2-dimensional as specified a few lines above with `self.input_spec = base_layer.InputSpec(ndim=2)`.

Did you get the `ValueError` while running a script that uses the `IndRNNCell`? If so, could you provide the code, so that I can try to reproduce it?

**Comment by Luonic** [comment]
@batzner i was just reading your implementation, not actually running code. Thank you for pointing out that input is 2D because I missed that)
I am going to give a try to your IndRNN for character-level sentiment analysis and will notify if any problems will occur
